name: Update Gulpease Index

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  gulpease:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SWE-project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Gulpease script
        run: |
          python scripts/gulpease.py

      - name: Checkout project-metrics
        uses: actions/checkout@v4
        with:
          repository: BitByBit-SWE/project-metrics
          token: ${{ secrets.METRICS_REPO_TOKEN }}
          path: project-metrics

      - name: Update CSV
        run: |
          cp project-metrics/data/gulpease_index.csv project-metrics/data/gulpease_index.csv || true
          cp ../project-metrics/data/gulpease_index.csv project-metrics/data/gulpease_index.csv

      - name: Commit and push
        run: |
            cd project-metrics
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add data/gulpease_index.csv
            git commit -m "chore(metrics): update Gulpease index" || echo "No changes"
            git push

